export interface Out {
    "tesla-tower": number; // 1
    "wireless-power-tower": number; // 1
    "satellite-substation": number; // 1
    "wind-turbine": number; // 1
    "thermal-power-plant": number; // 1
    "solar-panel": number; // 1
    accumulator: number; // 1
    "geothermal-power-station": number; // 1
    "mini-fusion-power-plant": number; // 1
    "energy-exchanger": number; // 1
    "ray-receiver": number; // 1
    "artificial-star": number; // 1
    "accumulator-full": number; // 1
    "conveyor-belt-1": number; // 3
    "conveyor-belt-2": number; // 3
    "conveyor-belt-3": number; // 3
    splitter: number; // 1
    "automatic-piler": number; // 1
    "traffic-monitor": number; // 1
    "spray-coater": number; // 1
    "storage-1": number; // 1
    "storage-2": number; // 1
    "storage-tank": number; // 1
    "logistics-distributor": number; // 1
    "planetary-logistics-station": number; // 1
    "interstellar-logistics-station": number; // 1
    "orbital-collector": number; // 1
    "sorter-1": number; // 1
    "sorter-2": number; // 2
    "sorter-3": number; // 2
    "sorter-4": number; // 1
    "mining-machine": number; // 1
    "advanced-mining-machine": number; // 1
    "water-pump": number; // 1
    "oil-extractor": number; // 1
    "oil-refinery": number; // 1
    fractionator: number; // 1
    "chemical-plant": number; // 1
    "quantum-chemical-plant": number; // 1
    "miniature-particle-collider": number; // 1
    "arc-smelter": number; // 1
    "plane-smelter": number; // 1
    "df-negentropy-smelter": number; // 1
    "assembling-machine-1": number; // 1
    "assembling-machine-2": number; // 1
    "assembling-machine-3": number; // 1
    "df-recomposing-assembler": number; // 1
    "matrix-lab": number; // 1
    "df-self-evolution-lab": number; // 1
    "em-rail-ejector": number; // 1
    "vertical-launching-silo": number; // 1
    "df-gauss-turret": number; // 1
    "df-missile-turret": number; // 1
    "df-implosion-cannon": number; // 1
    "df-laser-turret": number; // 1
    "df-plasma-turret": number; // 1
    "df-plasma-turret-sr": number; // 1
    "df-battlefield-analysis-base": number; // 1
    "df-jammer-tower": number; // 1
    "df-signal-tower": number; // 1
    "df-planetary-shield-generator": number; // 1
    "iron-ingot": number; // 1
    "copper-ingot": number; // 1
    "high-purity-silicon": number; // 1
    "titanium-ingot": number; // 1
    "stone-brick": number; // 1
    "energetic-graphite": number; // 1
    hydrogen: number; // 1, 3, 2, 7.68, 2.4
    "refined-oil": number; // 2, 3
    graphene: number; // 2
    plastic: number; // 1
    "proliferator-1": number; // 1
    "proliferator-2": number; // 1
    "proliferator-3": number; // 1
    "df-magnum-ammo-box": number; // 1
    "df-missile-set": number; // 1
    coal: number; // 1
    "copper-ore": number; // 1
    "critical-photon": number; // 6, 12
    "crude-oil": number; // 1
    "fire-ice": number; // 1, 5.6
    "fractal-silicon": number; // 1
    "iron-ore": number; // 1
    "kimberlite-ore": number; // 1
    water: number; // 1
    "optical-grating-crystal": number; // 1
    "organic-crystal": number; // 1
    "silicon-ore": number; // 1
    "spiniform-stalagmite-crystal": number; // 1
    stone: number; // 1
    "sulfuric-acid": number; // 1, 4
    "titanium-ore": number; // 1
    "unipolar-magnet": number; // 1
    magnet: number; // 1
    "magnetic-coil": number; // 2
    "crystal-silicon": number; // 1, 2
    "titanium-alloy": number; // 4
    glass: number; // 1
    diamond: number; // 1, 2
    "df-combustible-unit": number; // 1
    "df-explosive-unit": number; // 2
    "df-crystal-explosive-unit": number; // 8
    "df-titanium-ammo-box": number; // 1
    "df-supersonic-missile-set": number; // 2
    steel: number; // 1
    "electric-motor": number; // 1
    "titanium-glass": number; // 2
    prism: number; // 2
    "titanium-crystal": number; // 1
    "df-engine": number; // 1
    thruster: number; // 1
    "reinforced-thruster": number; // 1
    "df-superalloy-ammo-box": number; // 1
    "df-gravity-missile-set": number; // 3
    gear: number; // 1
    "electromagnetic-turbine": number; // 1
    "circuit-board": number; // 2
    "graviton-lens": number; // 1
    deuterium: number; // 0.01, 5, 0.32
    "carbon-nanotube": number; // 2
    "strange-matter": number; // 1
    "logistics-bot": number; // 1
    "logistics-drone": number; // 1
    "logistics-vessel": number; // 1
    "df-plasma-capsule": number; // 1
    "df-shell-set": number; // 1
    "plasma-exciter": number; // 1
    "super-magnetic-ring": number; // 1
    "particle-broadband": number; // 1
    processor: number; // 1
    "casimir-crystal": number; // 1
    "particle-container": number; // 1
    "solar-sail": number; // 2
    "frame-material": number; // 1
    "dyson-sphere-component": number; // 1
    "small-carrier-rocket": number; // 1
    "df-antimatter-capsule": number; // 1
    "df-high-explosive-shell-set": number; // 1
    "photon-combiner": number; // 1
    "microcrystalline-component": number; // 1
    "quantum-chip": number; // 1
    "plane-filter": number; // 1
    "annihilation-constraint-sphere": number; // 1
    "hydrogen-fuel-rod": number; // 2
    "deuteron-fuel-rod": number; // 2
    "antimatter-fuel-rod": number; // 2
    "df-strange-annihilation-fuel-rod": number; // 1
    "df-jamming-capsule": number; // 1
    "df-crystal-shell-set": number; // 1
    "df-prototype": number; // 1
    "df-precision-drone": number; // 1
    "df-attack-drone": number; // 1
    "df-corvette": number; // 1
    "df-destroyer": number; // 1
    "space-warper": number; // 1, 8
    antimatter: number; // 2
    "df-suppressing-capsule": number; // 2
    foundation: number; // 1
    "electromagnetic-matrix": number; // 1
    "energy-matrix": number; // 1
    "structure-matrix": number; // 1
    "information-matrix": number; // 1
    "gravity-matrix": number; // 2
    "universe-matrix": number; // 1
    "applied-superconductor": number; // 3600
    "artificial-star-technology": number; // 3600
    "automatic-metallurgy": number; // 3600
    "basic-assembling-processes": number; // 3600
    "basic-chemical-engineering": number; // 3600
    "basic-logistics-system": number; // 3600
    "casimir-crystal-technology": number; // 3600
    "controlled-annihilation-reaction": number; // 3600
    "crystal-smelting": number; // 3600
    "deuterium-fractionation-technology": number; // 3600
    "df-antimatter-capsule-tech": number; // 3600
    "df-attack-drone-tech": number; // 3600
    "df-battlefield-analysis-base-tech": number; // 3600
    "df-combustible-unit-tech": number; // 3600
    "df-corvette-tech": number; // 3600
    "df-crystal-explosive-unit-tech": number; // 3600
    "df-crystal-shell-set-tech": number; // 3600
    "df-destroyer-tech": number; // 3600
    "df-digital-analog-computation": number; // 3600
    "df-engine-tech": number; // 3600
    "df-explosive-unit-tech": number; // 3600
    "df-gravity-missile-set-tech": number; // 3600
    "df-high-density-controlled-annihilation": number; // 3600
    "df-high-explosive-shell-set-tech": number; // 3600
    "df-implosion-cannon-tech": number; // 3600
    "df-jammer-tower-tech": number; // 3600
    "df-matter-recombination": number; // 3600
    "df-missile-turret-tech": number; // 3600
    "df-negentropy-recursion": number; // 3600
    "df-planetary-defense-system": number; // 3600
    "df-plasma-turret-tech": number; // 3600
    "df-precision-drone-tech": number; // 3600
    "df-prototype-tech": number; // 3600
    "df-signal-tower-tech": number; // 3600
    "df-superalloy-ammo-box-tech": number; // 3600
    "df-supersonic-missile-set-tech": number; // 3600
    "df-suppressing-capsule-tech": number; // 3600
    "df-titanium-ammo-box-tech": number; // 3600
    "df-weapon-system": number; // 3600
    "dirac-inversion-mechanism": number; // 3600
    "distribution-logistics-system": number; // 3600
    "dyson-sphere-stress-system-1": number; // 3600
    "electromagnetic-drive": number; // 3600
    "electromagnetic-matrix-technology": number; // 3600
    electromagnetism: number; // 3600
    "energy-matrix-technology": number; // 3600
    "energy-storage": number; // 3600
    "environment-modification": number; // 3600
    "fluid-storage-encapsulation": number; // 3600
    "gas-giants-exploitation": number; // 3600
    "geothermal-extraction": number; // 3600
    "gravitational-wave-refraction": number; // 3600
    "gravity-matrix-technology": number; // 3600
    "high-efficiency-logistics-system": number; // 3600
    "high-efficiency-plasma-control": number; // 3600
    "high-speed-assembling-processes": number; // 3600
    "high-strength-crystal": number; // 3600
    "high-strength-glass": number; // 3600
    "high-strength-lightweight-structure": number; // 3600
    "high-strength-material": number; // 3600
    "high-strength-titanium-alloy": number; // 3600
    "hydrogen-fuel-rod-technology": number; // 3600
    "improved-logistics-system": number; // 3600
    "information-matrix-technology": number; // 3600
    "integrated-logistics-system": number; // 3600
    "interstellar-logistics-system": number; // 3600
    "interstellar-power-transmission": number; // 3600
    "magnetic-levitation-technology": number; // 3600
    "magnetic-particle-trap": number; // 3600
    "mesoscopic-quantum-entanglement": number; // 3600
    "mini-fusion-power-generation": number; // 3600
    "miniature-particle-collider-technology": number; // 3600
    "mission-completed": number; // 3600
    "particle-control-technology": number; // 3600
    "photon-frequency-conversion": number; // 3600
    "photon-spotlight-mining-technology": number; // 3600
    "plane-filter-smelting-technology": number; // 3600
    "planetary-ionosphere-utilization": number; // 3600
    "planetary-logistics-system": number; // 3600
    "plasma-extract-refining": number; // 3600
    "polymer-chemical-engineering": number; // 3600
    "processor-technology": number; // 3600
    "proliferator-1-technology": number; // 3600
    "proliferator-2-technology": number; // 3600
    "proliferator-3-technology": number; // 3600
    "quantum-chip-technology": number; // 3600
    "quantum-printing-technology": number; // 3600
    "ray-receiver-technology": number; // 3600
    "reforming-refine-technology": number; // 3600
    "reinforced-thruster-technology": number; // 3600
    "satellite-power-distribution-system": number; // 3600
    "semiconductor-material": number; // 3600
    "smelting-purification": number; // 3600
    "solar-collection": number; // 3600
    "solar-sail-orbit-system": number; // 3600
    "steel-smelting": number; // 3600
    "strange-matter-technology": number; // 3600
    "structure-matrix-technology": number; // 3600
    "super-magnetic-field-generator": number; // 3600
    "thermal-power": number; // 3600
    "thruster-technology": number; // 3600
    "titanium-smelting": number; // 3600
    "universe-matrix-technology": number; // 3600
    "vertical-launching-silo-technology": number; // 3600
    "wave-function-interference": number; // 3600
    "x-ray-cracking-technology": number; // 3600
    "communication-control-1": number; // 3600
    "communication-control-2": number; // 3600
    "communication-control-3": number; // 3600
    "communication-control-4": number; // 3600
    "communication-control-5": number; // 3600
    "communication-control-6": number; // 3600
    "communication-control-7": number; // 3600
    "df-auto-reconstruction-marking-1": number; // 3600
    "df-auto-reconstruction-marking-2": number; // 3600
    "df-auto-reconstruction-marking-3": number; // 3600
    "df-auto-reconstruction-marking-4": number; // 3600
    "df-auto-reconstruction-marking-5": number; // 3600
    "df-auto-reconstruction-marking-6": number; // 3600
    "df-combat-drone-attack-speed-1": number; // 3600
    "df-combat-drone-attack-speed-2": number; // 3600
    "df-combat-drone-attack-speed-3": number; // 3600
    "df-combat-drone-attack-speed-4": number; // 3600
    "df-combat-drone-attack-speed-5": number; // 3600
    "df-combat-drone-damage-1": number; // 3600
    "df-combat-drone-damage-2": number; // 3600
    "df-combat-drone-damage-3": number; // 3600
    "df-combat-drone-damage-4": number; // 3600
    "df-combat-drone-damage-5": number; // 3600
    "df-combat-drone-durability-1": number; // 3600
    "df-combat-drone-durability-2": number; // 3600
    "df-combat-drone-durability-3": number; // 3600
    "df-combat-drone-durability-4": number; // 3600
    "df-combat-drone-durability-5": number; // 3600
    "df-em-weapon-strength-1": number; // 3600
    "df-em-weapon-strength-2": number; // 3600
    "df-em-weapon-strength-3": number; // 3600
    "df-em-weapon-strength-4": number; // 3600
    "df-em-weapon-strength-5": number; // 3600
    "df-em-weapon-strength-6": number; // 3600
    "df-energy-shield-1": number; // 3600
    "df-energy-shield-2": number; // 3600
    "df-energy-shield-3": number; // 3600
    "df-energy-shield-4": number; // 3600
    "df-energy-shield-5": number; // 3600
    "df-energy-shield-6": number; // 3600
    "df-energy-shield-7": number; // 3600
    "df-energy-weapon-damage-1": number; // 3600
    "df-energy-weapon-damage-2": number; // 3600
    "df-energy-weapon-damage-3": number; // 3600
    "df-energy-weapon-damage-4": number; // 3600
    "df-energy-weapon-damage-5": number; // 3600
    "df-energy-weapon-damage-6": number; // 3600
    "df-enhanced-structure-1": number; // 3600
    "df-enhanced-structure-2": number; // 3600
    "df-enhanced-structure-3": number; // 3600
    "df-enhanced-structure-4": number; // 3600
    "df-enhanced-structure-5": number; // 3600
    "df-enhanced-structure-6": number; // 3600
    "df-explosive-weapon-damage-1": number; // 3600
    "df-explosive-weapon-damage-2": number; // 3600
    "df-explosive-weapon-damage-3": number; // 3600
    "df-explosive-weapon-damage-4": number; // 3600
    "df-explosive-weapon-damage-5": number; // 3600
    "df-explosive-weapon-damage-6": number; // 3600
    "df-ground-squadron-expansion-1": number; // 3600
    "df-ground-squadron-expansion-2": number; // 3600
    "df-ground-squadron-expansion-3": number; // 3600
    "df-ground-squadron-expansion-4": number; // 3600
    "df-ground-squadron-expansion-5": number; // 3600
    "df-ground-squadron-expansion-6": number; // 3600
    "df-ground-squadron-expansion-7": number; // 3600
    "df-kinetic-weapon-damage-1": number; // 3600
    "df-kinetic-weapon-damage-2": number; // 3600
    "df-kinetic-weapon-damage-3": number; // 3600
    "df-kinetic-weapon-damage-4": number; // 3600
    "df-kinetic-weapon-damage-5": number; // 3600
    "df-kinetic-weapon-damage-6": number; // 3600
    "df-planetary-shield-1": number; // 3600
    "df-planetary-shield-2": number; // 3600
    "df-planetary-shield-3": number; // 3600
    "df-planetary-shield-4": number; // 3600
    "df-planetary-shield-5": number; // 3600
    "df-space-fleet-expansion-1": number; // 3600
    "df-space-fleet-expansion-2": number; // 3600
    "df-space-fleet-expansion-3": number; // 3600
    "df-space-fleet-expansion-4": number; // 3600
    "df-space-fleet-expansion-5": number; // 3600
    "df-space-fleet-expansion-6": number; // 3600
    "df-space-fleet-expansion-7": number; // 3600
    "distribution-range-1": number; // 3600
    "distribution-range-2": number; // 3600
    "distribution-range-3": number; // 3600
    "distribution-range-4": number; // 3600
    "distribution-range-5": number; // 3600
    "drive-engine-1": number; // 3600
    "drive-engine-2": number; // 3600
    "drive-engine-3": number; // 3600
    "drive-engine-4": number; // 3600
    "drive-engine-5": number; // 3600
    "drive-engine-6": number; // 3600
    "drone-engine-1": number; // 3600
    "drone-engine-2": number; // 3600
    "drone-engine-3": number; // 3600
    "drone-engine-4": number; // 3600
    "drone-engine-5": number; // 3600
    "drone-engine-6": number; // 3600
    "energy-circuit-1": number; // 3600
    "energy-circuit-2": number; // 3600
    "energy-circuit-3": number; // 3600
    "energy-circuit-4": number; // 3600
    "energy-circuit-5": number; // 3600
    "energy-circuit-6": number; // 3600
    "inventory-capacity-1": number; // 3600
    "inventory-capacity-2": number; // 3600
    "inventory-capacity-3": number; // 3600
    "inventory-capacity-4": number; // 3600
    "inventory-capacity-5": number; // 3600
    "inventory-capacity-6": number; // 3600
    "inventory-capacity-7": number; // 3600
    "logistics-carrier-capacity-1": number; // 3600
    "logistics-carrier-capacity-12": number; // 3600
    "logistics-carrier-capacity-2": number; // 3600
    "logistics-carrier-capacity-3": number; // 3600
    "logistics-carrier-capacity-4": number; // 3600
    "logistics-carrier-capacity-5": number; // 3600
    "logistics-carrier-capacity-6": number; // 3600
    "logistics-carrier-capacity-7": number; // 3600
    "logistics-carrier-capacity-8": number; // 3600
    "logistics-carrier-capacity-9": number; // 3600
    "logistics-carrier-engine-1": number; // 3600
    "logistics-carrier-engine-2": number; // 3600
    "logistics-carrier-engine-3": number; // 3600
    "logistics-carrier-engine-4": number; // 3600
    "logistics-carrier-engine-5": number; // 3600
    "logistics-carrier-engine-6": number; // 3600
    "logistics-carrier-engine-7": number; // 3600
    "logistics-station-integrated-logistics-1": number; // 3600
    "logistics-station-integrated-logistics-2": number; // 3600
    "logistics-station-integrated-logistics-3": number; // 3600
    "mass-construction-1": number; // 3600
    "mass-construction-2": number; // 3600
    "mass-construction-3": number; // 3600
    "mass-construction-4": number; // 3600
    "mass-construction-5": number; // 3600
    "mecha-core-1": number; // 3600
    "mecha-core-2": number; // 3600
    "mecha-core-3": number; // 3600
    "mecha-core-4": number; // 3600
    "mecha-core-5": number; // 3600
    "mecha-core-6": number; // 3600
    "mechanical-frame-1": number; // 3600
    "mechanical-frame-2": number; // 3600
    "mechanical-frame-3": number; // 3600
    "mechanical-frame-4": number; // 3600
    "mechanical-frame-5": number; // 3600
    "mechanical-frame-6": number; // 3600
    "mechanical-frame-7": number; // 3600
    "mechanical-frame-8": number; // 3600
    "pile-sorter-1": number; // 3600
    "pile-sorter-2": number; // 3600
    "pile-sorter-3": number; // 3600
    "pile-sorter-4": number; // 3600
    "pile-sorter-5": number; // 3600
    "pile-sorter-6": number; // 3600
    "ray-transmission-efficiency-1": number; // 3600
    "ray-transmission-efficiency-2": number; // 3600
    "ray-transmission-efficiency-3": number; // 3600
    "ray-transmission-efficiency-4": number; // 3600
    "ray-transmission-efficiency-5": number; // 3600
    "ray-transmission-efficiency-6": number; // 3600
    "ray-transmission-efficiency-7": number; // 3600
    "ray-transmission-efficiency-8": number; // 3600
    "research-speed-1": number; // 3600
    "research-speed-2": number; // 3600
    "research-speed-3": number; // 3600
    "research-speed-4": number; // 3600
    "solar-sail-life-1": number; // 3600
    "solar-sail-life-2": number; // 3600
    "solar-sail-life-3": number; // 3600
    "solar-sail-life-4": number; // 3600
    "solar-sail-life-5": number; // 3600
    "solar-sail-life-6": number; // 3600
    "sorter-cargo-integration": number; // 3600
    "sorter-cargo-stacking-1": number; // 3600
    "sorter-cargo-stacking-2": number; // 3600
    "sorter-cargo-stacking-3": number; // 3600
    "sorter-cargo-stacking-4": number; // 3600
    "sorter-cargo-stacking-5": number; // 3600
    "universe-exploration-1": number; // 3600
    "universe-exploration-2": number; // 3600
    "universe-exploration-3": number; // 3600
    "universe-exploration-4": number; // 3600
    "veins-utilization-1": number; // 3600
    "veins-utilization-2": number; // 3600
    "veins-utilization-3": number; // 3600
    "veins-utilization-4": number; // 3600
    "veins-utilization-5": number; // 3600
    "veins-utilization-6": number; // 3600
    "vertical-construction-1": number; // 3600
    "vertical-construction-2": number; // 3600
    "vertical-construction-3": number; // 3600
    "vertical-construction-4": number; // 3600
    "vertical-construction-5": number; // 3600
    "vertical-construction-6": number; // 3600
  }