import type { In } from "./In";
import type { Out } from "./Out";

export interface Recipe {
    category: string; // buildings, components, technologies, upgrades
    id: string; // tesla-tower, wireless-power-tower, satellite-substation, wind-turbine, thermal-power-plant, solar-panel, accumulator, geothermal-power-station, mini-fusion-power-plant, energy-exchanger, ...
    name: string; // Tesla Tower, Wireless Power Tower, Satellite Substation, Wind Turbine, Thermal Power Plant, Solar Panel, Accumulator, Geothermal Power Station, Mini Fusion Power Plant, Energy Exchanger, ...
    time: number; // 1, 3, 5, 4, 6, 10, 15, 8, 30, 2, ...
    in: In; // {"iron-ingot":2,"magnetic-coil":1}, {"plasma-exciter":3,"tesla-tower":1}, {"frame-material":2,"super-magnetic-ring":10,"wireless-power-tower":1}, {"gear":1,"iron-ingot":6,"magnetic-coil":3}, {"gear":4,"iron-ingot":10,"magnetic-coil":4,"stone-brick":4}, {"circuit-board":5,"copper-ingot":10,"high-purity-silicon":10}, {"crystal-silicon":3,"iron-ingot":6,"super-magnetic-ring":1}, {"copper-ingot":20,"photon-combiner":4,"steel":15,"super-magnetic-ring":1}, {"carbon-nanotube":8,"processor":4,"super-magnetic-ring":10,"titanium-alloy":12}, {"particle-container":8,"processor":40,"steel":40,"titanium-alloy":40}, ...
    out: Out; // {"tesla-tower":1}, {"wireless-power-tower":1}, {"satellite-substation":1}, {"wind-turbine":1}, {"thermal-power-plant":1}, {"solar-panel":1}, {"accumulator":1}, {"geothermal-power-station":1}, {"mini-fusion-power-plant":1}, {"energy-exchanger":1}, ...
    producers: Array<string>; // ["assembling-machine-1","assembling-machine-2","assembling-machine-3","df-recom…, ["energy-exchanger"], ["arc-smelter","plane-smelter","df-negentropy-smelter"], ["oil-refinery"], ["chemical-plant","quantum-chemical-plant"], ["mining-machine","advanced-mining-machine"], ["ray-receiver"], ["ray-receiver-pro"], ["oil-extractor"], ["water-pump"], ...
    row: number; // 1, 0, 2, 3, 4, 5, 6, 7, 8, 9, ...
    flags?: Array<string>; // ["locked"], ["mining"], ["mining","locked"], ["technology"]
    icon?: string; // accumulator, gas-giants-exploitation
    usage?: number | string; // -54000, 5/3
    cost?: number; // 100, 200, 1
  }